### ISSUE TITLE
containerised applications do not survive a camera restart 

### ISSUE THREAD

**Issue by fire-ant** [AxisCommunications/docker-compose-acap#162]
### Describe the feature

Less a feature and more a requisite for production usage. Should anyone use the  [contianer-example](https://github.com/AxisCommunications/acap-native-sdk-examples/tree/main/container-example) pattern they will encounter an issue whereby if their camera is either gracefully restarted or externally rebooted the containers do not respawn. 

The root cause of the issue is that the paths which are recreated in the parent namespace are not removed prior to dockerd starting, resulting in the inability to create containers under /run/container in the user namespace.

You can see the dockerd-rootless.sh solves this by deleting the necessary paths  so dockerd/rootlesskit can administrate these appropriately https://github.com/moby/moby/blob/4318ab0b33888d155abea0366d9c066dad46cf6c/contrib/dockerd-rootless.sh#L144

### Added value

Any body availing of containerised applications which are managed by the runtime itself and not restarted externally will need this in order to have stable fault tolerant workloads.

### Additional context

N/A

**Comment by madelen-at-work** [comment]
Hi @fire-ant , Thank you for the feedback. We will investigate this.

**Comment by madelen-at-work** [comment]
This issue is fixed in [AXIS OS LTS 2024 11.11](https://help.axis.com/en-us/axis-os-release-notes#lts-2024-11-11) from 11.11.109. Upcoming [AXIS OS 12](https://help.axis.com/en-us/axis-os-release-notes#axis-os-12) will also have the fix.
